//
// Created by lukemartinlogan on 11/30/21.
//

#ifndef LABSTOR_RUNTIME_IDS_KERNEL_H
#define LABSTOR_RUNTIME_IDS_KERNEL_H

enum {
    SHMEM_MODULE_RUNTIME_ID,
    WORKER_MODULE_RUNTIME_ID,
    MQ_DRIVER_RUNTIME_ID,
    BIO_DRIVER_RUNTIME_ID,
    BLKDEV_TABLE_RUNTIME_ID
};

#endif //LABSTOR_RUNTIME_IDS_KERNEL_H
