//
// Created by lukemartinlogan on 11/18/21.
//

#ifndef LABSTOR_CLIENT_MACROS_H
#define LABSTOR_CLIENT_MACROS_H

#include <labstor/constants/macros.h>
#include <labstor/userspace/util/singleton.h>
#define LABSTOR_CONFIGURATION_MANAGER_CLASS labstor::Client::ConfigurationManager
#define LABSTOR_IPC_MANAGER_CLASS labstor::Client::IPCManager
#define LABSTOR_MODULE_MANAGER_CLASS labstor::Client::ModuleManager
#define LABSTOR_WORK_ORCHESTRATOR_CLASS labstor::Client::WorkOrchestrator
#define LABSTOR_NAMESPACE_CLASS labstor::Client::Namespace

#define LABSTOR_CONFIGURATION_MANAGER_T SINGLETON_T(LABSTOR_CONFIGURATION_MANAGER_CLASS)
#define LABSTOR_IPC_MANAGER_T SINGLETON_T(LABSTOR_IPC_MANAGER_CLASS)
#define LABSTOR_MODULE_MANAGER_T SINGLETON_T(LABSTOR_MODULE_MANAGER_CLASS)
#define LABSTOR_WORK_ORCHESTRATOR_T SINGLETON_T(LABSTOR_WORK_ORCHESTRATOR_CLASS)
#define LABSTOR_NAMESPACE_T SINGLETON_T(LABSTOR_NAMESPACE_CLASS)

#define LABSTOR_CONFIGURATION_MANAGER_SINGLETON scs::Singleton<LABSTOR_CONFIGURATION_MANAGER_CLASS>
#define LABSTOR_IPC_MANAGER_SINGLETON scs::Singleton<LABSTOR_IPC_MANAGER_CLASS>
#define LABSTOR_MODULE_MANAGER_SINGLETON scs::Singleton<LABSTOR_MODULE_MANAGER_CLASS>
#define LABSTOR_WORK_ORCHESTRATOR_SINGLETON scs::Singleton<LABSTOR_WORK_ORCHESTRATOR_CLASS>
#define LABSTOR_NAMESPACE_SINGLETON scs::Singleton<LABSTOR_NAMESPACE_CLASS>

#define LABSTOR_CONFIGURATION_MANAGER LABSTOR_CONFIGURATION_MANAGER_SINGLETON::GetInstance()
#define LABSTOR_IPC_MANAGER LABSTOR_IPC_MANAGER_SINGLETON::GetInstance()
#define LABSTOR_MODULE_MANAGER LABSTOR_MODULE_MANAGER_SINGLETON::GetInstance()
#define LABSTOR_WORK_ORCHESTRATOR LABSTOR_WORK_ORCHESTRATOR_SINGLETON::GetInstance()
#define LABSTOR_NAMESPACE LABSTOR_NAMESPACE_SINGLETON::GetInstance()

#endif //LABSTOR_CLIENT_MACROS_H
