modules:
  Dummy:
    client: ${LABSTOR_BUILD_DIR}/modules/dummy/libdummy_client.so
    server: ${LABSTOR_BUILD_DIR}/modules/dummy/libdummy_server.so
  BlkdevTable:
    client: ${LABSTOR_BUILD_DIR}/modules/kernel/blkdev_table/libblkdev_table_client.so
    server: ${LABSTOR_BUILD_DIR}/modules/kernel/blkdev_table/libblkdev_table_server.so
  MQDriver:
    client: ${LABSTOR_BUILD_DIR}/modules/kernel/mq_driver/libmq_driver_client.so
    server: ${LABSTOR_BUILD_DIR}/modules/kernel/mq_driver/libmq_driver_server.so
work_orchestrator:
  time_slice_us: 1000
  work_queue_depth: 128
  policy: round-robin
  kernel_workers:
    - {worker_id: 0, cpu_id: 1}
    - {worker_id: 1, cpu_id: 2}
  server_workers:
    - {worker_id: 0, cpu_id: 3}
    - {worker_id: 1, cpu_id: 4}
ipc_manager:
  pid_to_ipc_size_mb: 2
  qps_by_id_size_mb: 2
  max_collisions: 64

  allocator_unit_bytes: 128
  process_shmem_kb: 16

  kernel_shmem_mb: 1
  num_kernel_queues: 8
  kernel_queue_size_kb: 4
  kernel_request_unit_bytes: 64

  private_mem_mb: 2
  num_private_queues: 8
  private_queue_size_kb: 4
  private_request_unit_bytes: 128

namespace:
  max_entries: 1024
  max_collisions: 16
  shmem_request_unit: 128
  shmem_kb: 1024
admin_thread: 0