modules:
  secure_shmem:
      client: "/home/lukemartinlogan/Documents/Projects/PhD/labstor/cmake-build-debug/modules/kernel/secure_shmem/secure_shmem_client.so"
      server: "/home/lukemartinlogan/Documents/Projects/PhD/labstor/cmake-build-debug/modules/kernel/secure_shmem/secure_shmem_client.so"
work_orchestrator:
  time_slice_us: 1000
  policy: round-robin
  kernel_workers:
    - {worker_id: 1, cpu_id: 1}
    - {worker_id: 2, cpu_id: 2}
  server_workers:
    - {worker_id: 1, cpu_id: 3}
    - {worker_id: 2, cpu_id: 4}
ipc_manager:
  kernel_shmem_mb: 1
  internal_shmem_mb: 16
  process_shmem_kb: 16
  allocator_unit_bytes: 256
admin_thread: 0