modules:
  Dummy:
    client: ${LABSTOR_BUILD_DIR}/modules/dummy/libdummy_client.so
    server: ${LABSTOR_BUILD_DIR}/modules/dummy/libdummy_server.so
  IPCTest:
    client: ${LABSTOR_BUILD_DIR}/modules/kernel/ipc_test/libipc_test_client.so
    server: ${LABSTOR_BUILD_DIR}/modules/kernel/ipc_test/libipc_test_server.so
  BlkdevTable:
    client: ${LABSTOR_BUILD_DIR}/modules/kernel/blkdev_table/libblkdev_table_client.so
    server: ${LABSTOR_BUILD_DIR}/modules/kernel/blkdev_table/libblkdev_table_server.so
  MQDriver:
    client: ${LABSTOR_BUILD_DIR}/modules/kernel/mq_driver/libmq_driver_client.so
    server: ${LABSTOR_BUILD_DIR}/modules/kernel/mq_driver/libmq_driver_server.so
  BIODriver:
    client: ${LABSTOR_BUILD_DIR}/modules/kernel/bio_driver/libbio_driver_client.so
    server: ${LABSTOR_BUILD_DIR}/modules/kernel/bio_driver/libbio_driver_server.so
work_orchestrator:
  time_slice_us: 1000
  work_queue_depth: 128
  policy: round-robin
  kernel_workers:
    - {worker_id: 0, cpu_id: 0}
  server_workers:
    - {worker_id: 0, cpu_id: 2}
ipc_manager:
  pid_to_ipc_size_mb: 2
  qps_by_id_size_mb: 2
  max_collisions: 64

  client:
    max_region_size_kb: 64
    num_queues: 1
    queue_depth: 100
    request_unit_bytes: 64
    min_request_region_kb: 32

  kernel:
    max_region_size_kb: 1024
    num_queues: 1
    queue_depth: 1024
    request_unit_bytes: 64
    min_request_region_kb: 500

  private:
    max_region_size_kb: 1024
    num_queues: 1
    queue_depth: 1024
    request_unit_bytes: 64
    min_request_region_kb: 500

namespace:
  max_entries: 1024
  max_collisions: 16
  shmem_request_unit: 128
  shmem_kb: 1024
admin_thread: 0