//
// Created by lukemartinlogan on 11/28/21.
//

#ifndef LABSTOR_KERNEL_CLIENT_MACROS_H
#define LABSTOR_KERNEL_CLIENT_MACROS_H

#include <labstor/userspace/util/singleton.h>
#define LABSTOR_KERNEL_CLIENT_CLASS labstor::Kernel::NetlinkClient
#define LABSTOR_KERNEL_IPC_MANAGER_CLASS labstor::kernel::netlink::IPCManager
#define LABSTOR_KERNEL_WORK_ORCHESTRATOR_CLASS labstor::kernel::netlink::WorkerClient
#define LABSTOR_KERNEL_SHMEM_ALLOC_CLASS labstor::kernel::netlink::ShmemClient

#define LABSTOR_KERNEL_CLIENT_T SINGLETON_T(LABSTOR_KERNEL_CLIENT_CLASS)
#define LABSTOR_KERNEL_IPC_MANAGER_T SINGLETON_T(LABSTOR_KERNEL_IPC_MANAGER_CLASS)
#define LABSTOR_KERNEL_WORK_ORCHESTRATOR_T SINGLETON_T(LABSTOR_KERNEL_WORK_ORCHESTRATOR_CLASS)
#define LABSTOR_KERNEL_SHMEM_ALLOC_T SINGLETON_T(LABSTOR_KERNEL_SHMEM_ALLOC_CLASS)

#define LABSTOR_KERNEL_CLIENT_SINGLETON scs::Singleton<LABSTOR_KERNEL_CLIENT_CLASS>
#define LABSTOR_KERNEL_IPC_MANAGER_SINGLETON scs::Singleton<LABSTOR_KERNEL_IPC_MANAGER_CLASS>
#define LABSTOR_KERNEL_WORK_ORCHESTRATOR_SINGLETON scs::Singleton<LABSTOR_KERNEL_WORK_ORCHESTRATOR_CLASS>
#define LABSTOR_KERNEL_SHMEM_ALLOC_SINGLETON scs::Singleton<LABSTOR_KERNEL_SHMEM_ALLOC_CLASS>

#define LABSTOR_KERNEL_CLIENT LABSTOR_KERNEL_CLIENT_SINGLETON::GetInstance()
#define LABSTOR_KERNEL_IPC_MANAGER LABSTOR_KERNEL_IPC_MANAGER_SINGLETON::GetInstance()
#define LABSTOR_KERNEL_WORK_ORCHESTRATOR LABSTOR_KERNEL_WORK_ORCHESTRATOR_SINGLETON::GetInstance()
#define LABSTOR_KERNEL_SHMEM_ALLOC LABSTOR_KERNEL_SHMEM_ALLOC_SINGLETON::GetInstance()

#endif //LABSTOR_KERNEL_CLIENT_MACROS_H
