//
// Created by lukemartinlogan on 11/26/21.
//

#ifndef LABSTOR_CONSTANTS_H
#define LABSTOR_CONSTANTS_H

#define LABSTOR_REQUEST_SUCCESS 0
#define LABSTOR_REQUEST_FAILED -1000

#define LABSTOR_INVALID_NAMESPACE_KEY -1

#define LABSTOR_REGISTRAR_ID 0

enum {
    IPC_TEST_MODULE_RUNTIME_ID,
    SHMEM_MODULE_RUNTIME_ID,
    IPC_MANAGER_MODULE_RUNTIME_ID,
    WORKER_MODULE_RUNTIME_ID,
    MQ_DRIVER_RUNTIME_ID,
    BLKDEV_TABLE_RUNTIME_ID
};

#endif //LABSTOR_CONSTANTS_H
